version: '3.8'

services:
  springboot-app:
    build: .
    container_name: url-shortener-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: UrlShortenerdb
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
